FROM mcr.microsoft.com/dotnet/aspnet:3.1
COPY bin/Release/netcoreapp3.1/publish/ WebAppForContainer/
WORKDIR /WebAppForContainer
EXPOSE 5000
ENTRYPOINT ["dotnet", "ContainerWebApplication1.dll","--host=0.0.0.0"]