FROM mcr.microsoft.com/dotnet/sdk:3.1
RUN mkdir /AppForContainer
WORKDIR /AppForContainer
COPY bin/Release/netcoreapp3.1/publish/ AppForContainer/
WORKDIR /AppForContainer
ENTRYPOINT ["dotnet", "ContainerConsoleApp1.dll"]